#!/bin/sh

# source ./activate

# run with input.txt
function r() {
	if [ ! -f "input.txt" ]; then
		echo "No input.txt"
		exit 1
	fi
	bat input.txt
	if [ -f "package.yaml" ]; then
		stack run
	elif [ -f "Cargo.toml" ]; then
		cargo run
	else
		echo 'No project found'
	fi < input.txt
}

# paste input to input.txt
function p() { 
	xclip -selection clipboard -o > input.txt
}

# test program with clipboard as input
function t() {
	p && r
}

# copy code to clipboard
function c() {
	code=''
	if [ -f "package.yaml" ]; then
		code='Main.hs'
	elif [ -f "Cargo.toml" ]; then
		code='main.rs'
	else
		echo 'No project found'
	fi
	code="src/$code"
	xclip -selection clipboard < "$code"
	echo "Copied $code to clipboard"
}
