name: copium

dependencies:
- base >= 4.7 && < 5
- array

ghc-options:
- -Wall

executables:
  copium:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
